#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Service.Application/Service.Application.csproj", "Service.Application/"]
RUN dotnet restore "Service.Application/Service.Application.csproj"
COPY . .
WORKDIR "/src/Service.Application"
RUN dotnet build "Service.Application.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Service.Application.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Service.Application.dll"]